website/begeleider/views.py
from flask import Blueprint, render_template, redirect, url_for
from website import db
from website.models import Begeleider
from website.begeleider.forms import VoegtoeBegeleider

# Definiëren van de begeleiders blueprint met de bijbehorende URL-prefix en template-folder
begeleiders_blueprint = Blueprint('begeleiders',
                                  __name__,
                                  template_folder='templates/begeleiders')

# Route voor het toevoegen van een begeleider
@begeleiders_blueprint.route('/toevoegen', methods=['GET', 'POST'])
def toevoegen():
    form = VoegtoeBegeleider()

    if form.validate_on_submit():
        naam = form.naam.data
        id = form.id.data
        
        # Controleren of de begeleider al bestaat op basis van ID
        existing_begeleider = Begeleider.query.filter_by(id=id).first()
        if existing_begeleider:
            existing_begeleider.naam = naam  # Naam bijwerken als de begeleider al bestaat
        else:
            new_begeleider = Begeleider(naam=naam, stage_id=id)
            db.session.add(new_begeleider)
        
        db.session.commit()
        return redirect(url_for('stages.lijst')) # Doorverwijzen naar de lijst met stages na toevoegen van begeleider
    
    return render_template('begeleider_toevoegen.html', form=form)

website/instelling/views.py
from flask import Blueprint, render_template, redirect, url_for
from website import db
from website.models import Instelling
from website.instelling.forms import VoegtoeInstelling

# Definiëren van de instellingen blueprint met de bijbehorende URL-prefix en template-folder
instellingen_blueprint = Blueprint('instellingen',
                                   __name__,
                                   template_folder="templates/instellingen")

# Route voor het toevoegen van een instelling
@instellingen_blueprint.route('/toevoegen', methods=['GET', 'POST'])
def toevoegen():
    form = VoegtoeInstelling()

    if form.validate_on_submit():
        naam = form.naam.data
        soort = form.soort.data
        id = form.id.data
        
        # Controleren of de instelling al bestaat op basis van ID
        existing_instelling = Instelling.query.filter_by(id=id).first()
        if existing_instelling:
            existing_instelling.naam = naam  # Naam bijwerken als de instelling al bestaat
            existing_instelling.soort = soort  # Soort bijwerken als de instelling al bestaat
        else:
            new_instelling = Instelling(naam=naam, soort=soort, stage_id=id)
            db.session.add(new_instelling)
        
        db.session.commit()
        return redirect(url_for('stages.lijst')) # Doorverwijzen naar de lijst met stages na toevoegen van instelling
    
    return render_template('instelling_toevoegen.html', form=form)

website/stage/views.py
from flask import Blueprint, render_template, redirect, url_for
from website import db
from website.stage.forms import VoegtoeForm, VerwijderForm
from website.models import Stage

# Definiëren van stages blueprint met de bijbehorende URL-prefix en template folder
stages_blueprint = Blueprint('stages',
                             __name__,
                             template_folder='templates/stages')

# Route voor het toevoegen van een stage
@stages_blueprint.route('/toevoegen', methods=['GET', 'POST'])
def toevoegen():
    form = VoegtoeForm()

    if form.validate_on_submit():
        periode = form.periode.data
        cijfer = form.cijfer.data
        naam = form.naam.data

        n_stage = Stage(periode, cijfer, naam)
        db.session.add(n_stage)
        db.session.commit()
        return redirect(url_for('stages.lijst')) # Doorverwijzen naar de lijst met stages na toevoegen van stage
    
    return render_template('toevoegen.html', form=form)

# Route voor het weergeven van de lijst met stages
@stages_blueprint.route('lijst')
def lijst():
    stages = Stage.query.all()
    return render_template('lijst.html', stages=stages)

# Route voor het verwijderen van een stage
@stages_blueprint.route('/verwijderen', methods=['GET', 'POST'])
def verwijderen():
    form = VerwijderForm()
    
    if form.validate_on_submit():
        id = form.id.data
        stag = Stage.query.get(id)
        db.session.delete(stag)
        db.session.commit()

        return redirect(url_for('stages.lijst')) # Doorverwijzen naar de lijst met stages na verwijderen van stage
    
    return render_template('verwijderen.html', form=form)

website/student/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from website import db
from website.models import Student
from website.student.forms import VoegtoeStudent

# Definiëren van de studenten blueprint met bijbehorende URL-prefix en template folder
studenten_blueprint = Blueprint('studenten',
                                __name__,
                                template_folder='templates/studenten')

# Route voor het toevoegen van een student
@studenten_blueprint.route('/toevoegen', methods=['GET', 'POST'])
def toevoegen():
    form = VoegtoeStudent()

    if form.validate_on_submit():
        naam = form.naam.data
        id = form.id.data
        
        # Controleren of de student al bestaat op basis van ID
        existing_student = Student.query.filter_by(id=id).first()
        if existing_student:
            existing_student.naam = naam  # Naam bijwerken als de student al bestaat
        else:
            new_student = Student(naam=naam, stage_id=id)
            db.session.add(new_student)
        
        db.session.commit()
        return redirect(url_for('stages.lijst')) # Doorverwijzen naar de lijst met stages na toevoegen van student
    
    return render_template('student_toevoegen.html', form=form)

website/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Stageapplicatie</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="navbar-nav">
        <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>
        <a class="nav-item nav-link" href="{{ url_for('stages.lijst') }}">Toon stages</a>
        {% if current_user.is_authenticated %}
        <a class="nav-item nav-link" href="{{ url_for('stages.toevoegen') }}">Voeg stage toe</a>
        <a class="nav-item nav-link" href="{{ url_for('stages.verwijderen') }}">Verwijder stage</a>
        <a class="nav-item nav-link" href="{{ url_for('studenten.toevoegen') }}">Voeg student toe</a>
        <a class="nav-item nav-link" href="{{ url_for('begeleiders.toevoegen') }}">Voeg begeleider toe</a>
        <a class="nav-item nav-link" href="{{ url_for('instellingen.toevoegen') }}">Voeg instelling toe</a>
        <a class="nav-item nav-link" href="{{ url_for('logout') }}">Uitloggen</a>
        {% else %}
        <a class="nav-item nav-link" href="{{ url_for('login')}}">Inloggen</a>
        <a class="nav-item nav-link" href="{{ url_for('register')}}">Registreren</a>
        {% endif %}
    </div>

</nav>

{% block content %}

{% endblock %}
</body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    {% if current_user.is_authenticated %}
    <p> Welkom {{ current_user.username }}!</p>
    {% else %}
    <h1>Stageapplicatie</h1>
    <p>Bekijk hier het stageoverzicht of log in / registreer om gegevens toe te voegen en te verwijderen.</p>
    {% endif %}  {# Add this line to close the if block #}
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" class="mt-4">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.email.label(class="form-label") }}
                    {{ form.email(class="form-control") }}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-label") }}
                    {{ form.password(class="form-control") }}
                </div>

                <div class="form-group">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" class="mt-4">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.email.label(class="form-label") }}
                    {{ form.email(class="form-control") }}
                </div>

                <div class="form-group">
                    {{ form.username.label(class="form-label") }}
                    {{ form.username(class="form-control") }}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-label") }}
                    {{ form.password(class="form-control") }}
                </div>

                <div class="form-group">
                    {{ form.pass_confirm.label(class="form-label") }}
                    {{ form.pass_confirm(class="form-control") }}
                </div>

                <div class="form-group">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/welkom.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        {% if current_user.is_authenticated %}
            <h1>Welkom, {{ current_user.username }}!</h1>
            <p class="lead">Leuk dat je er bent.</p>
            <p class="lead">Klik op een van de menubalkitems om verder te gaan.</p>
        {% else %}
            <h1 class="display-4">Stageapplicatie</h1>
            <p class="lead">Bekijk hier het stageoverzicht of log in / registreer om gegevens toe te voegen en te verwijderen.</p>
        {% endif %}
    </div>
</div>
{% endblock %}